### ISSUE TITLE
hostname box truncated in statistics webpage title

### ISSUE THREAD

**Issue by castorfou** [PomDev2/wlanpoke#5]
Hi POMDev,

my boxes are following the following name pattern: Squeezebox kitchen, Squeezebox Touch, Squeezebox bathroom...
When displaying webpage statistics, title of the page is always Squeezebox statistics for all boxes.
My guess is that it doesn't like the space in their names.

I think it is in awstats.sh.
But I don't understand how HOSTNAME is setup (HOSTNAME=`echo $VersWLP | cut -d" " -f1`) 

this is very very minor. (very)

**Comment by PomDev2** [comment]
That's right. The scripts expect a one-word host name, and you have shown that they will use just the first word of a multi-word name (on the bright side, instead of crashing!). This occurs because parsing and dealing with more than one "argument" is too complicated using shell (ash) script, and the script is quite long as it is.

_But I don't understand how HOSTNAME is setup_

It all starts in wlanpoke line 86:
HOSTNAME=`cat /etc/squeezeplay/userpath/settings/SlimDiscovery.lua | grep -o 'name=\"[^\"]*' | cut -d "\"" -f 2`
This awful kludge uses an undocumented entry in a lua executable file that is written by the Squeezeplay software. It cuts on double quotes as a delimiter, so this might preserve multiple word host names (never tested).

This HOSTNAME is written to the "Version" file on line 462:
`echo "$HOSTNAME ${ScriptName##*/} $Version" "launched $tsLaunch $tuLaunch Options: $Options" > "$APPDIR"/Version`

awstats.sh reads this file on line 32:
VersWLP=`cat "Version"`

then, on line 35:
HOSTNAME=`echo $VersWLP | cut -d" " -f1`
which is another cut operation that parses (-d" ") single "words" separated by spaces.

Assuming that 'Version" has the correct multi-word host name, It may be feasible to parse the host name as whatever comes before the script name, which is typically "wlanpoke.sh". This is a variable because interested experimenters (i.e., hackers) might want to try different versions of the script, which would have different file names (with version #s) to distinguish them. They may or may not end in ".sh". 

Please feel free to modify your software and let us know if and how you have solved this issue with a solution that would work for everyone. You can report back using this issue here. When resolved, it could be publicized on the forums as a patch or possibly included in a new release.

Thank you for the report.

**Comment by PomDev2** [comment]
I see that your wlanpoke fork has the radio name saved separately, which seems like a good solution to me.
